### ISSUE TITLE
Core:Save doesn't work with this

### ISSUE THREAD

**Issue by rolyataylor2** [aki77/atom-sequential-command#1]
"sequential-command":
    "commands": [
      {
        "name": "seq:save",
        "commands": [
          "auto-indent:apply",
          "core:Save",
          "seq:return"
        ]
      },

Does execute auto-indent, Does not save the file

**Comment by aki77** [comment]
It will be run in the following order when you run the `seq:save` command.
1. `auto-indent:apply`
2. `core:save`
3. `seq:return`
4. `auto-indent:apply`
5. `core:save`

...
